import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import hydra
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf

# NOTE:
# this script may need to be adjusted to your cluster environment,
# e.g. GPU directives, conda setup, and module system.

# THE FOLDER STRUCTURE GENERATED BY THE SCRIPT
# concrete_experiment
# ├── hydra_setup
# │   └── ...
# ├── hydra_run
# │   └── ...
# ├── src
# │   └── ...
# ├── artifacts
# │   └── ...
# ├── wandb
# │   └── ...
# ├── slurm
# │   ├── %j.out
# │   └── %j.err
# ├── hydra_setup.log
# ├── hydra_run.log
# ├── output.log
# ├── curr_train_script.py
# ├── curr_experiment_config.yaml
# └── curr_launch_script.sh


@hydra.main(
    version_base="1.3",
    config_path="../../experiments",
    config_name="number_vs_complexity_of_neuron_enwik8",
)
def submit_job(cfg: DictConfig):
    ########## DEFINE PATHS ##########

    exp_dir = Path(os.getcwd())
    slurm_dir = exp_dir / "slurm"
    src_dir = exp_dir / "src"
    experiment_name = HydraConfig.get().job.config_name
    curr_train_script_path = str(exp_dir / "curr_train_script.py")
    curr_experiment_config_path = str(exp_dir / "curr_experiment_config.yaml")
    curr_launch_script_path = str(exp_dir / "curr_launch_script.sh")
    curr_job_name = f"{experiment_name};{HydraConfig.get().job.override_dirname}"

    # previous run detection
    if os.path.isdir(slurm_dir):
        print(f"Previous runs encountered unexpectedly; aborting run...")
        sys.exit(1)

    ########## CREATE BASH SCRIPT ##########

    launch_script_lines = [
        "#!/bin/bash -l",
        f"#SBATCH -J {curr_job_name}",
        f"#SBATCH -D {exp_dir}",
        f"#SBATCH -o {slurm_dir}/%j.out",
        f"#SBATCH -e {slurm_dir}/%j.err",
        "",
        f"#SBATCH --partition={cfg.setup.slurm_partition}",
        "#SBATCH --nodes=1",
        "#SBATCH --ntasks=1",
        f"#SBATCH --cpus-per-task={cfg.setup.slurm_cpus}",
        f"#SBATCH --mem={cfg.setup.slurm_memory_gb}G",
        f"#SBATCH --time={cfg.setup.slurm_timeout_h}:00:00",
        f"#SBATCH --gres=gpu:{cfg.setup.slurm_gpu_type}:{cfg.setup.slurm_gpus}",
        "",
        "echo '---------- Configuring Environment ----------'",
        "echo 'Slurm Job Info:'",
        "scontrol show job ${SLURM_JOB_ID}",
        "echo 'NVIDIA SMI Info:'",
        "nvidia-smi",
        "echo 'Clearing Loaded Modules...'",
        "module purge",
        "echo 'Setting Environment Variables...'",
        f"export OMP_NUM_THREADS={int(cfg.setup.slurm_cpus)}",
        f"export CSTM_PRLL_EXEC=1",
        f"export PYTHONHASHSEED={cfg.setup.seed}",
        "echo 'Activating Conda Environment...'",
        f"source {cfg.setup.conda_install_path}",
        f"export PATH={src_dir}:$PATH",
        f"conda activate {cfg.setup.conda_env_name}",
        "",
        "echo '---------- Launching Experiment ----------'",
        (
            f"python {curr_train_script_path} "
            f"hydra.run.dir='.' "
            f"hydra.job.chdir='true' "
            f"hydra.output_subdir='hydra_run' "
            f"hydra.job.name='hydra_run' "
            f"+setup.wandb_group_name='{experiment_name}' "
            f"> output.log 2>&1"
        ),
        "echo '---------- Experiment Finished ----------'",
    ]
    launch_script = "\n".join(launch_script_lines)

    ########## SERIALIZE SCRIPTS ##########

    # create subfolders
    os.makedirs(slurm_dir)

    # copy train script
    shutil.copy(
        str(
            Path(cfg.setup.custom_code_folder) / "training" / cfg.training.train_script
        ),
        curr_train_script_path,
    )

    # save config yaml
    yaml_str = OmegaConf.to_yaml(cfg)
    with open(curr_experiment_config_path, "w") as file:
        file.write(yaml_str)

    # save launch script
    with open(curr_launch_script_path, "w") as f:
        f.write(launch_script)

    # copy src directory
    ignore_dirs = ["__pycache__", ".ipynb_checkpoints", ".DS_Store"]
    shutil.copytree(
        cfg.setup.custom_code_folder,
        src_dir,
        ignore=shutil.ignore_patterns(*ignore_dirs),
    )

    ########## LAUNCH SCRIPTS ##########

    result = subprocess.run(
        ["sbatch", curr_launch_script_path],
        check=True,
        capture_output=True,
        text=True,
    )
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S,%f")[:-3]
    if result.stdout:
        print(f"[{timestamp}][SLURM] {result.stdout.strip()}")
    if result.stderr:
        print(f"[{timestamp}][SLURM] {result.stderr.strip()}")


if __name__ == "__main__":
    submit_job()
