import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import hydra
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf

# THE FOLDER STRUCTURE GENERATED BY THE SCRIPT
# concrete_experiment
# ├── hydra_setup
# │   └── ...
# ├── hydra_run
# │   └── ...
# ├── src
# │   └── ...
# ├── artifacts
# │   └── ...
# ├── wandb
# │   └── ...
# ├── output.log
# ├── curr_train_script.py
# ├── curr_experiment_config.yaml
# └── curr_launch_script.sh


@hydra.main(
    version_base="1.3",
    config_path="../../experiments",
    config_name="number_vs_complexity_of_neuron_enwik8",
)
def run_local(cfg: DictConfig):
    ########## DEFINE PATHS ##########

    exp_dir = Path(os.getcwd())
    src_dir = exp_dir / "src"
    artifacts_dir = exp_dir / "artifacts"

    custom_code_folder = Path(
        os.path.expandvars(os.path.expanduser(str(cfg.setup.custom_code_folder)))
    )
    conda_install_path = os.path.expandvars(
        os.path.expanduser(str(cfg.setup.conda_install_path))
    )

    experiment_name = HydraConfig.get().job.config_name
    curr_train_script_path = exp_dir / "curr_train_script.py"
    curr_experiment_config_path = exp_dir / "curr_experiment_config.yaml"
    curr_launch_script_path = exp_dir / "curr_launch_script.sh"
    output_log_path = exp_dir / "output.log"

    # previous run detection
    previous_run_paths = [
        src_dir,
        artifacts_dir,
        curr_train_script_path,
        curr_experiment_config_path,
        curr_launch_script_path,
        output_log_path,
    ]
    if any(path.exists() for path in previous_run_paths):
        print("Previous run encountered unexpectedly; aborting run...")
        sys.exit(1)

    ########## CREATE BASH SCRIPT ##########

    launch_script_lines = [
        "#!/bin/bash -l",
        "set -eo pipefail",
        "",
        "echo '---------- Configuring Local Environment ----------'",
        f"cd '{exp_dir}'",
        "echo 'Working Directory:'",
        "pwd",
        "",
        "echo 'Setting Environment Variables...'",
        f"export PYTHONHASHSEED={cfg.setup.seed}",
        f"export PYTHONPATH='{exp_dir}':${{PYTHONPATH:-}}",
        "",
        "echo 'Activating Conda Environment...'",
        f"source '{conda_install_path}'",
        f"conda activate '{cfg.setup.conda_env_name}'",
        "",
        "echo 'Python executable:'",
        "which python",
        "python --version",
        "",
        "echo '---------- Launching Experiment ----------'",
        (
            f"python -u '{curr_train_script_path}' "
            f"hydra.run.dir='.' "
            f"hydra.job.chdir='true' "
            f"hydra.output_subdir='hydra_run' "
            f"hydra.job.name='hydra_run' "
            f"+setup.wandb_group_name='{experiment_name}' "
            f"2>&1 | tee '{output_log_path}'"
        ),
        "echo '---------- Experiment Finished ----------'",
    ]
    launch_script = "\n".join(launch_script_lines)

    ########## SERIALIZE SCRIPTS ##########

    # copy train script
    shutil.copy(
        str(custom_code_folder / "training" / cfg.training.train_script),
        curr_train_script_path,
    )

    # save config yaml
    yaml_str = OmegaConf.to_yaml(cfg)
    with open(curr_experiment_config_path, "w") as file:
        file.write(yaml_str)

    # save launch script
    with open(curr_launch_script_path, "w") as f:
        f.write(launch_script)

    # copy src directory
    ignore_dirs = ["__pycache__", ".ipynb_checkpoints", ".DS_Store"]
    shutil.copytree(
        custom_code_folder,
        src_dir,
        ignore=shutil.ignore_patterns(*ignore_dirs),
    )

    ########## LAUNCH SCRIPT ##########

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S,%f")[:-3]
    print(f"[{timestamp}][LOCAL] Launching local experiment...")

    subprocess.run(
        ["bash", "-l", str(curr_launch_script_path)],
        cwd=exp_dir,
        check=True,
    )

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S,%f")[:-3]
    print(f"[{timestamp}][LOCAL] Local experiment finished.")


if __name__ == "__main__":
    run_local()
